name: Run Blog Creator Regularly

on:
  schedule:
    # Har 2 ghante mein chalega (0 minute par, har 2nd ghante)
    - cron: '0 */2 * * *'
  workflow_dispatch: # Isse aap GitHub UI se manually run kar sakte ho

jobs:
  run-script:
    runs-on: ubuntu-latest # Linux server par chalega

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Apne code ko server par laane ke liye

    - name: Set up Python
      uses: actions/setup-python@v5 # Python environment setup karega
      with:
        python-version: '3.12' # Aap apni pasand ka Python version chun sakte hain (e.g., '3.10', '3.11', '3.12')

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Apni saari zaroori libraries install karega, jismein OAuth wali bhi hain
        pip install -r requirements.txt google-api-python-client google-auth-httplib2 google-auth-oauthlib markdown2

    - name: Run Python script
      env:
        # Apne GitHub Secrets se API keys aur credentials ko env variables mein pass karo
        GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        BLOGGER_BLOG_ID: ${{ secrets.BLOGGER_BLOG_ID }} # Apni Blogger Blog ID yahan se aayegi
        # --- Naye SECRETS FOR OAuth CLIENT ID ---
        GOOGLE_CLIENT_SECRETS_JSON: ${{ secrets.GOOGLE_CLIENT_SECRETS_JSON }} # client_secrets.json ka content
        GOOGLE_OAUTH_TOKEN_JSON: ${{ secrets.GOOGLE_OAUTH_TOKEN_JSON }}     # token_blogger.json ka content
        TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }} 

        CI: 'true' # Yeh script ko batata hai ki yeh CI environment mein chal raha hai, taaki browser flow skip ho

        # Uncomment aur set karo agar branding logo file repository mein hai:
        # BRANDING_LOGO_PATH: 'my_logo.png'
      run: |
        python main.py

    # Yeh step generated files ko upload karta hai taaki tum unhe download kar sako.
    - name: Upload Generated Blogs and Images
      uses: actions/upload-artifact@v4
      with:
        name: generated-blogs-and-images-${{ github.run_id }}
        path: |
          blog_drafts/
          transformed_images/